# fly.toml
app = 'watcher-sukanta'
primary_region = 'bom'

[build]
  dockerfile = 'docker/Dockerfile'

[deploy]
  strategy = 'canary'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = 'uvicorn server.main:app --host 0.0.0.0 --port 8000'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1